# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: dzon-os
description: My personal immutable OS with Nix and gaming tools.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      - https://dl.google.com/linux/chrome/rpm/stable/x86_64
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
    install:
      packages:
        - google-chrome-stable
        - steam
        - fastfetch
        - micro
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.equicord.equibop
          - com.visualstudio.code
          - com.jetbrains.Toolbox
          - com.bambulab.BambuStudio
          - org.godotengine.Godot
          - com.heroicgameslauncher.hgl
          - org.prismlauncher.PrismLauncher
          - org.vinegarhq.Sober
        shell:
          - flatpak install --system -y /usr/share/flatpaks/hytale.flatpak

  - type: script
    scripts:
      - setnix.sh
      - installtoolbox.sh

  - type: signing